training_dataset: /Users/marku/Documents/DT_prediction_model/DOLPHINN/data/WaveDir_30_Option2_SOV.csv
dof:
  # - "PtfmTDX_Floater"
  # - "PtfmTDY_Floater"
  # - "PtfmTDZ_Floater"
  # - "Vx_Floater_local"
  # - "Vy_Floater_local"
  # - "Vz_Floater_local"

  - "PtfmTDX_SOV"
  - "PtfmTDY_SOV"
  - "PtfmTDZ_SOV"
  - "Vx_SOV_local"
  - "Vy_SOV_local"
  - "Vz_SOV_local"

  # - "telescoping"
  # - "luffing"
  # - "slewing"
  # - "telescoping_vel"
  # - "luffing_vel"
  # - "slewing_vel"
unit:
  - "[m]"
  - "[m]"
  - "[m]"
  - "[m/s]"
  - "[m/s]"
  - "[m/s]"

  # - "[m]"
  # - "[m]"
  # - "[m]"
  # - "[m/s]"
  # - "[m/s]"
  # - "[m/s]"

  # - "m"
  # - "deg"
  # - "deg"
  # - "[m/s]"
  # - "[deg/s]"
  # - "[deg/s]"
conversion:
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  # - 1
  # - 1
  # - 1
  # - 1
  # - 1
  # - 1

time_horizon: 60
nm: 0.90
hidden_layer: 1
neuron_number: 110
epochs: 20
batch_time: 25
timestep: 1.0
lr: 0.001
dropout: 0.0005
train_ratio: 0.7
valid_ratio: 0.25
wind_prediction: False
wave_prediction: True
