batch_time: 40
conversion:
- 1
- 1
- 1
- 1
- 1
- 1
- 1
- 1
- 1
- 1
- 1
- 1
dof:
- PtfmTDX_Floater
- PtfmTDY_Floater
- PtfmTDZ_Floater
- Vx_Floater_local
- Vy_Floater_local
- Vz_Floater_local
- PtfmTDX_SOV
- PtfmTDY_SOV
- PtfmTDZ_SOV
- Vx_SOV_local
- Vy_SOV_local
- Vz_SOV_local
dropout: 0.005
epochs: 50
hidden_layer: 1
lr: 0.002
neuron_number: 110
nm: 0.95
time_horizon: 20
timestep: 1.0
train_ratio: 0.7
training_dataset: /Users/marku/Documents/DT_prediction_model/DOLPHINN/data/WaveDir_0_Option1.csv
unit:
- '[m]'
- '[m]'
- '[m]'
- '[m/s]'
- '[m/s]'
- '[m/s]'
- '[m]'
- '[m]'
- '[m]'
- '[m/s]'
- '[m/s]'
- '[m/s]'
valid_ratio: 0.25
wave_prediction: true
wind_prediction: false
